In [2]:
import cffi
import numba
import numba.core.typing.cffi_utils as cffi_support
import numpy as np

import ufl
from dolfinx.cpp.fem import Form_float64
from dolfinx.jit import ffcx_jit
from dolfinx import fem, mesh, io

from mpi4py import MPI
from petsc4py import PETSc

In [3]:
# Create mesh and function space
domain = mesh.create_unit_square(MPI.COMM_WORLD, 1, 1)
V = fem.FunctionSpace(domain, ("Lagrange", 1))

# Unpack mesh and dofmap data
num_owned_cells = domain.topology.index_map(domain.topology.dim).size_local
num_cells = num_owned_cells + domain.topology.index_map(domain.topology.dim).num_ghosts
x_dofs = domain.geometry.dofmap.array.reshape(num_cells, 3)
x = domain.geometry.x
dofmap = V.dofmap.list.array.reshape(num_cells, 3).astype(np.dtype(PETSc.IntType))

ffcxtype = "double"
nptype = "float64"

ffi = cffi.FFI()
cffi_support.register_type(ffi.typeof("double"), numba.types.float64)
c_signature = numba.types.void(
    numba.types.CPointer(numba.typeof(PETSc.ScalarType())),
    numba.types.CPointer(numba.typeof(PETSc.ScalarType())),
    numba.types.CPointer(numba.typeof(PETSc.ScalarType())),
    numba.types.CPointer(numba.types.double),
    numba.types.CPointer(numba.types.int32),
    numba.types.CPointer(numba.types.uint8))

@numba.njit(fastmath=True)
def assemble_vector_ufc(b, kernel, mesh, dofmap, num_cells):
    """Assemble provided FFCx/UFC kernel over a mesh into the array b"""
    v, x = mesh
    entity_local_index = np.array([0], dtype=np.intc)
    perm = np.array([0], dtype=np.uint8)
    geometry = np.zeros((3, 3))
    coeffs = np.zeros(1, dtype=PETSc.ScalarType)
    constants = np.zeros(1, dtype=PETSc.ScalarType)

    b_local = np.zeros(3, dtype=PETSc.ScalarType)
    for cell in range(num_cells):
        # FIXME: This assumes a particular geometry dof layout
        for j in range(3):
            geometry[j] = x[v[cell, j], :]
        b_local.fill(0.0)
        kernel(ffi.from_buffer(b_local), ffi.from_buffer(coeffs),
               ffi.from_buffer(constants),
               ffi.from_buffer(geometry), ffi.from_buffer(entity_local_index),
               ffi.from_buffer(perm))
        for j in range(3):
            b[dofmap[cell, j]] += b_local[j]

In [4]:
f = 1
const = fem.Constant(domain, PETSc.ScalarType(f))
coeff = fem.Function(fem.FunctionSpace(domain, ('DG', 0)))
coeff.vector.set(f)

In [5]:
# Test against generated code and general assembler
v = ufl.TestFunction(V)
L = ufl.inner(f, v) * ufl.dx
b1 = fem.petsc.assemble_vector(fem.form(L))
print("Correct linear form: ", b1[:])

b3 = fem.Function(V)
b = b3.x.array
b[:] = 0.0
ufcx_form, _, _ = ffcx_jit(domain.comm, L, form_compiler_params={"scalar_type": ffcxtype})
kernel = getattr(ufcx_form.integrals(0)[0], f"tabulate_tensor_{nptype}")
assemble_vector_ufc(b, kernel, (x_dofs, x), dofmap, num_owned_cells)
print('lin form after assemble_vector_ufc with direct constant in the form:', b3.x.array[:])

L = ufl.inner(const, v) * ufl.dx
b4 = fem.Function(V)
b = b4.x.array
b[:] = 0.0
ufcx_form, _, _ = ffcx_jit(domain.comm, L, form_compiler_params={"scalar_type": ffcxtype})
kernel_const = getattr(ufcx_form.integrals(0)[0], f"tabulate_tensor_{nptype}")
assemble_vector_ufc(b, kernel_const, (x_dofs, x), dofmap, num_owned_cells)
print('lin form after assemble_vector_ufc with fem.Constant in the form:', b4.x.array[:])

L = ufl.inner(coeff, v) * ufl.dx
b5 = fem.Function(V)
b = b5.x.array
b[:] = 0.0
ufcx_form, _, _ = ffcx_jit(domain.comm, L, form_compiler_params={"scalar_type": ffcxtype})
kernel_coeff = getattr(ufcx_form.integrals(0)[0], f"tabulate_tensor_{nptype}")
assemble_vector_ufc(b, kernel_coeff, (x_dofs, x), dofmap, num_owned_cells)
print('lin form after assemble_vector_ufc with fem.Constant in the form:', b5.x.array[:])

Correct linear form:  [0.33333333 0.16666667 0.33333333 0.16666667]
lin form after assemble_vector_ufc with direct constant in the form: [0.33333333 0.16666667 0.33333333 0.16666667]
lin form after assemble_vector_ufc with fem.Constant in the form: [0. 0. 0. 0.]
lin form after assemble_vector_ufc with fem.Constant in the form: [0. 0. 0. 0.]


In [6]:
##### cpp/dolfinx/fem/Form.h:

# /// @brief Type of integral
# enum class IntegralType : std::int8_t
# {
#   cell = 0,           ///< Cell
#   exterior_facet = 1, ///< Exterior facet
#   interior_facet = 2, ///< Interior facet
#   vertex = 3          ///< Vertex
# };

# /// @brief A representation of finite element variational forms.
# ///
# /// A note on the order of trial and test spaces: FEniCS numbers
# /// argument spaces starting with the leading dimension of the
# /// corresponding tensor (matrix). In other words, the test space is
# /// numbered 0 and the trial space is numbered 1. However, in order to
# /// have a notation that agrees with most existing finite element
# /// literature, in particular
# ///
# ///  \f[   a = a(u, v)        \f]
# ///
# /// the spaces are numbered from right to left
# ///
# ///  \f[   a: V_1 \times V_0 \rightarrow \mathbb{R}  \f]
# ///
# /// This is reflected in the ordering of the spaces that should be
# /// supplied to generated subclasses. In particular, when a bilinear
# /// form is initialized, it should be initialized as `a(V_1, V_0) =
# /// ...`, where `V_1` is the trial space and `V_0` is the test space.
# /// However, when a form is initialized by a list of argument spaces
# /// (the variable `function_spaces` in the constructors below), the list
# /// of spaces should start with space number 0 (the test space) and then
# /// space number 1 (the trial space).

# template <typename T>
# class Form
# {
# public:
#   /// @brief Create a finite element form.
#   ///
#   /// @note User applications will normally call a fem::Form builder
#   /// function rather using this interfcae directly.
#   ///
#   /// @param[in] function_spaces Function spaces for the form arguments
#   /// @param[in] integrals The integrals in the form. The first key is
#   /// the domain type. For each key there is a pair (list[domain id,
#   /// integration kernel], domain markers).
#   /// @param[in] coefficients
#   /// @param[in] constants Constants in the Form
#   /// @param[in] needs_facet_permutations Set to true is any of the
#   /// integration kernels require cell permutation data
#   /// @param[in] mesh The mesh of the domain. This is required when
#   /// there are not argument functions from which the mesh can be
#   /// extracted, e.g. for functionals

In [7]:
@numba.cfunc(c_signature, nopython=True)
def tabulate_lin_form_b(b_, w_, c_, coords_, local_index, orientation):
    b = numba.carray(b_, (3), dtype=PETSc.ScalarType)      
    b_tmp = np.zeros((3), dtype=PETSc.ScalarType)
    w = numba.carray(w_, (1), dtype=PETSc.ScalarType)
    w[0] = 1 # Changing of the coefficient value on an element !
    kernel_coeff(ffi.from_buffer(b_tmp), w_, c_, coords_, local_index, orientation)
    b[:] = b_tmp

    # It works the same way:
    # 1) kernel_coeff(b_, w_, c_, coords_, local_index, orientation)
    # 2) b = numba.carray(b_, (3), dtype=PETSc.ScalarType)      
    #    kernel_coeff(ffi.from_buffer(b), w_, c_, coords_, local_index, orientation)

integrals = {fem.IntegralType.cell: ([(-1, tabulate_lin_form_b.address)], None)}
L = Form_float64([V._cpp_object], integrals, [coeff._cpp_object], [], False)
b = fem.petsc.assemble_vector(L)
print('lin form after any sort of tabulation', b[:])

@numba.cfunc(c_signature, nopython=True)
def tabulate_lin_form_b_coeff(b_, w_, c_, coords_, local_index, orientation=ffi.NULL):
    b = numba.carray(b_, (3), dtype=PETSc.ScalarType)
    w = numba.carray(w_, (1), dtype=PETSc.ScalarType)
    c = numba.carray(c_, (1), dtype=PETSc.ScalarType)
    coordinate_dofs = numba.carray(coords_, (3, 3), dtype=np.float64)
    x0, y0 = coordinate_dofs[0, :2]
    x1, y1 = coordinate_dofs[1, :2]
    x2, y2 = coordinate_dofs[2, :2]

    # 2x Element area Ae
    Ae = abs((x0 - x1) * (y2 - y1) - (y0 - y1) * (x2 - x1))
    b[:] = c[0] * Ae / 6.0

integrals = {fem.IntegralType.cell: ([(-1, tabulate_lin_form_b_coeff.address)], None)}
L = Form_float64([V._cpp_object], integrals, [coeff._cpp_object], [const._cpp_object], False)
b = fem.petsc.assemble_vector(L)
print('lin form after direct calculation', b[:])

lin form after any sort of tabulation [0.33333333 0.16666667 0.33333333 0.16666667]
lin form after direct calculation [0.33333333 0.16666667 0.33333333 0.16666667]


In [8]:
u, v = ufl.TrialFunction(V), ufl.TestFunction(V)
a = ufl.inner( f * u, v ) * ufl.dx
A = fem.petsc.assemble_matrix(fem.form(a))
A.assemble()
print('Correct bil form \n', A[:, :])

Correct bil form 
 [[0.16666667 0.04166667 0.08333333 0.04166667]
 [0.04166667 0.08333333 0.04166667 0.        ]
 [0.08333333 0.04166667 0.16666667 0.04166667]
 [0.04166667 0.         0.04166667 0.08333333]]


In [9]:
ufcx_form, _, _ = ffcx_jit(domain.comm, a, form_compiler_params={"scalar_type": ffcxtype})
kernel_a = getattr(ufcx_form.integrals(0)[0], f"tabulate_tensor_{nptype}")

@numba.cfunc(c_signature, nopython=True)
def tabulate_tensor_A(A_, w_, c_, coords_, entity_local_index, permutation):
    # A = numba.carray(A_, (3, 3), dtype=PETSc.ScalarType)
    kernel_a(A_, w_, c_, coords_, entity_local_index, permutation)


integrals = {fem.IntegralType.cell: ([(-1, tabulate_tensor_A.address)], None)}
a_form = Form_float64([V._cpp_object, V._cpp_object], integrals, [], [], False, None)
A = fem.petsc.assemble_matrix(a_form)
A.assemble()
print(A[:, :])  

[[0.16666667 0.04166667 0.08333333 0.04166667]
 [0.04166667 0.08333333 0.04166667 0.        ]
 [0.08333333 0.04166667 0.16666667 0.04166667]
 [0.04166667 0.         0.04166667 0.08333333]]


In [10]:
a = ufl.inner( const * u, v ) * ufl.dx

ufcx_form, _, _ = ffcx_jit(domain.comm, a, form_compiler_params={"scalar_type": ffcxtype})
kernel_a = getattr(ufcx_form.integrals(0)[0], f"tabulate_tensor_{nptype}")

@numba.cfunc(c_signature, nopython=True)
def tabulate_tensor_A(A_, w_, c_, coords_, entity_local_index, permutation):
    # A = numba.carray(A_, (3, 3), dtype=PETSc.ScalarType)
    kernel_a(A_, w_, c_, coords_, entity_local_index, permutation)

integrals = {fem.IntegralType.cell: ([(-1, tabulate_tensor_A.address)], None)}
a_form = Form_float64([V._cpp_object, V._cpp_object], integrals, [], [const._cpp_object], False, None)
A = fem.petsc.assemble_matrix(a_form)
A.assemble()
print(A[:, :])  

[[0.16666667 0.04166667 0.08333333 0.04166667]
 [0.04166667 0.08333333 0.04166667 0.        ]
 [0.08333333 0.04166667 0.16666667 0.04166667]
 [0.04166667 0.         0.04166667 0.08333333]]


In [11]:
a = ufl.inner( const * u, v ) * ufl.dx

ufcx_form, _, _ = ffcx_jit(domain.comm, a, form_compiler_params={"scalar_type": ffcxtype})
kernel_a = getattr(ufcx_form.integrals(0)[0], f"tabulate_tensor_{nptype}")

@numba.cfunc(c_signature, nopython=True)
def tabulate_tensor_A(A_, w_, c_, coords_, entity_local_index, permutation):
    # A = numba.carray(A_, (3, 3), dtype=PETSc.ScalarType)
    c_[0] = 2 # !!!!!
    kernel_a(A_, w_, c_, coords_, entity_local_index, permutation)

integrals = {fem.IntegralType.cell: ([(-1, tabulate_tensor_A.address)], None)}
a_form = Form_float64([V._cpp_object, V._cpp_object], integrals, [], [const._cpp_object], False, None)
A = fem.petsc.assemble_matrix(a_form)
A.assemble()
print(A[:, :])  

[[0.33333333 0.08333333 0.16666667 0.08333333]
 [0.08333333 0.16666667 0.08333333 0.        ]
 [0.16666667 0.08333333 0.33333333 0.08333333]
 [0.08333333 0.         0.08333333 0.16666667]]


In [12]:
a = ufl.inner( coeff * u, v ) * ufl.dx

ufcx_form, _, _ = ffcx_jit(domain.comm, a, form_compiler_params={"scalar_type": ffcxtype})
kernel_a = getattr(ufcx_form.integrals(0)[0], f"tabulate_tensor_{nptype}")

@numba.cfunc(c_signature, nopython=True)
def tabulate_tensor_A(A_, w_, c_, coords_, entity_local_index, permutation):
    w_[0] = 2 # !!!!!
    kernel_a(A_, w_, c_, coords_, entity_local_index, permutation)

integrals = {fem.IntegralType.cell: ([(-1, tabulate_tensor_A.address)], None)}
a_form = Form_float64([V._cpp_object, V._cpp_object], integrals, [coeff._cpp_object], [const._cpp_object], False, None)
A = fem.petsc.assemble_matrix(a_form)
A.assemble()
print(A[:, :])  

[[0.33333333 0.08333333 0.16666667 0.08333333]
 [0.08333333 0.16666667 0.08333333 0.        ]
 [0.16666667 0.08333333 0.33333333 0.08333333]
 [0.08333333 0.         0.08333333 0.16666667]]


In [13]:
V = fem.VectorFunctionSpace(domain, ("Lagrange", 1))
u, v = ufl.TrialFunction(V), ufl.TestFunction(V)

const = fem.Constant(domain, (PETSc.ScalarType(1), PETSc.ScalarType(1)))

L = ufl.inner(const, v) * ufl.dx
b1 = fem.petsc.assemble_vector(fem.form(L))
print("Correct linear form:\n", b1[:])

# coeff = fem.Function(fem.FunctionSpace(domain, ('DG', 0)))
# coeff.vector.set(f)

# a = ufl.inner( f * u, v ) * ufl.dx
# A = fem.petsc.assemble_matrix(fem.form(a))
# A.assemble()
# print('Correct bil form \n', A[:, :])

Correct linear form:
 [0.33333333 0.33333333 0.16666667 0.16666667 0.33333333 0.33333333
 0.16666667 0.16666667]


In [14]:
L = ufl.inner(const, v) * ufl.dx

ufcx_form, _, _ = ffcx_jit(domain.comm, L, form_compiler_params={"scalar_type": ffcxtype})
kernel_b = getattr(ufcx_form.integrals(0)[0], f"tabulate_tensor_{nptype}")

@numba.cfunc(c_signature, nopython=True)
def tabulate_lin_form_b(b_, w_, c_, coords_, local_index, orientation):
    c = numba.carray(c_, (2), dtype=PETSc.ScalarType)
    c[0] = 0 # Changing of the coefficient value on an element !
    kernel_b(b_, w_, c_, coords_, local_index, orientation)
    
integrals = {fem.IntegralType.cell: ([(-1, tabulate_lin_form_b.address)], None)}
L = Form_float64([V._cpp_object], integrals, [], [const._cpp_object], False)
b = fem.petsc.assemble_vector(L)
print(b[:])

[0.         0.33333333 0.         0.16666667 0.         0.33333333
 0.         0.16666667]


In [15]:
a = ufl.inner( coeff * u, v ) * ufl.dx
A = fem.petsc.assemble_matrix(fem.form(a))
A.assemble()
print(A[:, :])

[[0.16666667 0.         0.04166667 0.         0.08333333 0.
  0.04166667 0.        ]
 [0.         0.16666667 0.         0.04166667 0.         0.08333333
  0.         0.04166667]
 [0.04166667 0.         0.08333333 0.         0.04166667 0.
  0.         0.        ]
 [0.         0.04166667 0.         0.08333333 0.         0.04166667
  0.         0.        ]
 [0.08333333 0.         0.04166667 0.         0.16666667 0.
  0.04166667 0.        ]
 [0.         0.08333333 0.         0.04166667 0.         0.16666667
  0.         0.04166667]
 [0.04166667 0.         0.         0.         0.04166667 0.
  0.08333333 0.        ]
 [0.         0.04166667 0.         0.         0.         0.04166667
  0.         0.08333333]]


In [16]:
coeff2 = fem.Function(fem.FunctionSpace(domain, ('DG', 0)))
coeff2.vector.set(5)

a = ufl.inner( coeff * u, v * coeff2) * ufl.dx

ufcx_form, _, _ = ffcx_jit(domain.comm, a, form_compiler_params={"scalar_type": ffcxtype})
kernel_a = getattr(ufcx_form.integrals(0)[0], f"tabulate_tensor_{nptype}")

@numba.cfunc(c_signature, nopython=True)
def tabulate_tensor_A(A_, w_, c_, coords_, entity_local_index, permutation):
    kernel_a(A_, w_, c_, coords_, entity_local_index, permutation)

integrals = {fem.IntegralType.cell: ([(-1, tabulate_tensor_A.address)], None)}
a_form = Form_float64([V._cpp_object, V._cpp_object], integrals, [coeff._cpp_object, coeff2._cpp_object], [const._cpp_object], False, None)
A = fem.petsc.assemble_matrix(a_form)
A.assemble()
print(A[:, :])  

[[0.83333333 0.         0.20833333 0.         0.41666667 0.
  0.20833333 0.        ]
 [0.         0.83333333 0.         0.20833333 0.         0.41666667
  0.         0.20833333]
 [0.20833333 0.         0.41666667 0.         0.20833333 0.
  0.         0.        ]
 [0.         0.20833333 0.         0.41666667 0.         0.20833333
  0.         0.        ]
 [0.41666667 0.         0.20833333 0.         0.83333333 0.
  0.20833333 0.        ]
 [0.         0.41666667 0.         0.20833333 0.         0.83333333
  0.         0.20833333]
 [0.20833333 0.         0.         0.         0.20833333 0.
  0.41666667 0.        ]
 [0.         0.20833333 0.         0.         0.         0.20833333
  0.         0.41666667]]


In [17]:
def epsilon(u):
    return ufl.sym(ufl.grad(u))

def sigma(u):
    return 1*ufl.div(u)*ufl.Identity(u.geometric_dimension()) + 2*1*epsilon(u)

a = ufl.inner( sigma(u), epsilon(v) ) * ufl.dx

A = fem.petsc.assemble_matrix(fem.form(a))
A.assemble()
print(A[:, :])

[[ 2.   0.  -1.5  0.5  0.  -1.  -0.5  0.5]
 [ 0.   2.   0.5 -0.5 -1.   0.   0.5 -1.5]
 [-1.5  0.5  2.  -1.  -0.5  0.5  0.   0. ]
 [ 0.5 -0.5 -1.   2.   0.5 -1.5  0.   0. ]
 [ 0.  -1.  -0.5  0.5  2.   0.  -1.5  0.5]
 [-1.   0.   0.5 -1.5  0.   2.   0.5 -0.5]
 [-0.5  0.5  0.   0.  -1.5  0.5  2.  -1. ]
 [ 0.5 -1.5  0.   0.   0.5 -0.5 -1.   2. ]]


In [18]:
coeff1 = fem.Function(fem.FunctionSpace(domain, ('DG', 0)))
coeff2 = fem.Function(fem.FunctionSpace(domain, ('DG', 0)))
coeff1.vector.set(1)
coeff2.vector.set(1)

def epsilon(u):
    return ufl.sym(ufl.grad(u))

def sigma(u):
    return coeff1*ufl.div(u)*ufl.Identity(u.geometric_dimension()) + 2*coeff2*epsilon(u)

a = ufl.inner( sigma(u), epsilon(v) ) * ufl.dx

ufcx_form, _, _ = ffcx_jit(domain.comm, a, form_compiler_params={"scalar_type": ffcxtype})
kernel_a = getattr(ufcx_form.integrals(0)[0], f"tabulate_tensor_{nptype}")

@numba.cfunc(c_signature, nopython=True)
def tabulate_tensor_A(A_, w_, c_, coords_, entity_local_index, permutation):
    w_[0] = 10
    w_[1] = 1000
    kernel_a(A_, w_, c_, coords_, entity_local_index, permutation)

integrals = {fem.IntegralType.cell: ([(-1, tabulate_tensor_A.address)], None)}
a_form = Form_float64([V._cpp_object, V._cpp_object], integrals, [coeff1._cpp_object, coeff2._cpp_object], [const._cpp_object], False, None)
A = fem.petsc.assemble_matrix(a_form)
A.assemble()
print(A[:, :])  

[[ 515.    0. -510.  500.    0. -505.   -5.    5.]
 [   0.  515.    5.   -5. -505.    0.  500. -510.]
 [-510.    5.  515. -505.   -5.  500.    0.    0.]
 [ 500.   -5. -505.  515.    5. -510.    0.    0.]
 [   0. -505.   -5.    5.  515.    0. -510.  500.]
 [-505.    0.  500. -510.    0.  515.    5.   -5.]
 [  -5.  500.    0.    0. -510.    5.  515. -505.]
 [   5. -510.    0.    0.  500.   -5. -505.  515.]]


In [19]:
lambda_ = 1
mu_ = 1
C = np.zeros(shape=(3,3), dtype=PETSc.ScalarType)
C = np.array([[lambda_ + 2*mu_, lambda_, 0],
              [lambda_, lambda_ + 2*mu_, 0],
              [0, 0, 2*mu_]], dtype=PETSc.ScalarType)
C_const = fem.Constant(domain, C)

coeff1 = fem.Function(fem.FunctionSpace(domain, ('DG', 0)))
coeff2 = fem.Function(fem.FunctionSpace(domain, ('DG', 0)))
coeff1.vector.set(1)
coeff2.vector.set(1)

def epsilon(u):
    return ufl.sym(ufl.grad(u))

def as_2D_tensor(X):
    return ufl.as_tensor([[X[0], X[2]],
                          [X[2], X[1]]])

def sigma(u):
    eps = epsilon(u)
    # return coeff1*ufl.div(u)*ufl.Identity(u.geometric_dimension()) + 2*coeff2*epsilon(u)
    return as_2D_tensor(C_const * ufl.as_vector([eps[0,0], eps[1,1], eps[0,1]]))

a = ufl.inner( sigma(u), epsilon(v) ) * ufl.dx

ufcx_form, _, _ = ffcx_jit(domain.comm, a, form_compiler_params={"scalar_type": ffcxtype})
kernel_a = getattr(ufcx_form.integrals(0)[0], f"tabulate_tensor_{nptype}")

@numba.cfunc(c_signature, nopython=True)
def tabulate_tensor_A(A_, w_, c_, coords_, entity_local_index, permutation):
    # w_[0] = 10
    # w_[1] = 1000
    c = numba.carray(c_, (3, 3), dtype=PETSc.ScalarType)
    # c[0][0] = 100 
    kernel_a(A_, w_, c_, coords_, entity_local_index, permutation)

integrals = {fem.IntegralType.cell: ([(-1, tabulate_tensor_A.address)], None)}
a_form = Form_float64([V._cpp_object, V._cpp_object], integrals, [coeff1._cpp_object, coeff2._cpp_object], [C_const._cpp_object], False, None)
A = fem.petsc.assemble_matrix(a_form)
A.assemble()
print(A[:, :])  


[[ 2.   0.  -1.5  0.5  0.  -1.  -0.5  0.5]
 [ 0.   2.   0.5 -0.5 -1.   0.   0.5 -1.5]
 [-1.5  0.5  2.  -1.  -0.5  0.5  0.   0. ]
 [ 0.5 -0.5 -1.   2.   0.5 -1.5  0.   0. ]
 [ 0.  -1.  -0.5  0.5  2.   0.  -1.5  0.5]
 [-1.   0.   0.5 -1.5  0.   2.   0.5 -0.5]
 [-0.5  0.5  0.   0.  -1.5  0.5  2.  -1. ]
 [ 0.5 -1.5  0.   0.   0.5 -0.5 -1.   2. ]]


In [20]:
dx = ufl.Measure(
    "dx",
    domain=domain,
    metadata={"quadrature_degree": 2, "quadrature_scheme": "default"},
)

lambda_ = 1
mu_ = 1
C = np.array([[lambda_ + 2*mu_, lambda_, 0],
              [lambda_, lambda_ + 2*mu_, 0],
              [0, 0, 2*mu_]], dtype=PETSc.ScalarType)
C_const = fem.Constant(domain, C)

def epsilon(u):
    return ufl.sym(ufl.grad(u))

def as_2D_tensor(X):
    return ufl.as_tensor([[X[0], X[2]],
                          [X[2], X[1]]])

def sigma(u):
    eps = epsilon(u)
    return as_2D_tensor(C_const * ufl.as_vector([eps[0,0], eps[1,1], eps[0,1]]))

a = ufl.inner( sigma(u), epsilon(v) ) * dx

ufcx_form, _, _ = ffcx_jit(domain.comm, a, form_compiler_params={"scalar_type": ffcxtype})
kernel_a = getattr(ufcx_form.integrals(0)[0], f"tabulate_tensor_{nptype}")

@numba.cfunc(c_signature, nopython=True)
def tabulate_tensor_A(A_, w_, c_, coords_, entity_local_index, permutation):
    # c = numba.carray(c_, (3, 3), dtype=PETSc.ScalarType)
    kernel_a(A_, w_, c_, coords_, entity_local_index, permutation)

integrals = {fem.IntegralType.cell: ([(-1, tabulate_tensor_A.address)], None)}
a_form = Form_float64([V._cpp_object, V._cpp_object], integrals, [], [C_const._cpp_object], False, None)
A = fem.petsc.assemble_matrix(a_form)
A.assemble()
print(A[:, :])  

[[ 2.   0.  -1.5  0.5  0.  -1.  -0.5  0.5]
 [ 0.   2.   0.5 -0.5 -1.   0.   0.5 -1.5]
 [-1.5  0.5  2.  -1.  -0.5  0.5  0.   0. ]
 [ 0.5 -0.5 -1.   2.   0.5 -1.5  0.   0. ]
 [ 0.  -1.  -0.5  0.5  2.   0.  -1.5  0.5]
 [-1.   0.   0.5 -1.5  0.   2.   0.5 -0.5]
 [-0.5  0.5  0.   0.  -1.5  0.5  2.  -1. ]
 [ 0.5 -1.5  0.   0.   0.5 -0.5 -1.   2. ]]


In [21]:
# V = fem.FunctionSpace(domain, ("Lagrange", 1))
# W0e = ufl.FiniteElement("Quadrature", domain.ufl_cell(), degree=2, quad_scheme='default')
# W = fem.FunctionSpace(domain, W0e)

# @numba.cfunc(c_signature, nopython=True)
# def tabulate_lin_form_b_coeff(b_, w_, c_, coords_, local_index, orientation=ffi.NULL):
#     b = numba.carray(b_, (10), dtype=PETSc.ScalarType)
#     # w = numba.carray(w_, (1), dtype=PETSc.ScalarType)
#     # c = numba.carray(c_, (1), dtype=PETSc.ScalarType)
#     # coordinate_dofs = numba.carray(coords_, (3, 3), dtype=np.float64)
#     # x0, y0 = coordinate_dofs[0, :2]
#     # x1, y1 = coordinate_dofs[1, :2]
#     # x2, y2 = coordinate_dofs[2, :2]
#     # coordinate_dofs = numba.carray(coords_, (20), dtype=np.float64)

#     # 2x Element area Ae
#     # Ae = abs((x0 - x1) * (y2 - y1) - (y0 - y1) * (x2 - x1))
#     b[:] = coords_[4]

# integrals = {fem.IntegralType.cell: ([(-1, tabulate_lin_form_b_coeff.address)], None)}
# L = Form_float64([W._cpp_object], integrals, [], [const._cpp_object], False)
# b = fem.petsc.assemble_vector(L)
# print('lin form after direct calculation', b[:])

In [22]:
f = 1
const = fem.Constant(domain, PETSc.ScalarType(f))
coeff = fem.Function(fem.FunctionSpace(domain, ('DG', 0)))
coeff.vector.set(f)

V = fem.FunctionSpace(domain, ("Lagrange", 1))
v = ufl.TestFunction(V)

@numba.njit(fastmath=True)
def assemble_vector_ufc(b, kernel, mesh, dofmap, num_cells):
    """Assemble provided FFCx/UFC kernel over a mesh into the array b"""
    v, x = mesh
    entity_local_index = np.array([0], dtype=np.intc)
    perm = np.array([0], dtype=np.uint8)
    geometry = np.zeros((3, 3))
    coeffs = np.zeros(1, dtype=PETSc.ScalarType)
    constants = np.array([1], dtype=PETSc.ScalarType)

    b_local = np.zeros(3, dtype=PETSc.ScalarType)
    for cell in range(num_cells):
        # FIXME: This assumes a particular geometry dof layout
        for j in range(3):
            geometry[j] = x[v[cell, j], :]
        b_local.fill(0.0)
        kernel(ffi.from_buffer(b_local), ffi.from_buffer(coeffs),
               ffi.from_buffer(constants),
               ffi.from_buffer(geometry), ffi.from_buffer(entity_local_index),
               ffi.from_buffer(perm))
        for j in range(3):
            b[dofmap[cell, j]] += b_local[j]

L = ufl.inner(const, v) * ufl.dx
b4 = fem.Function(V)
b = b4.x.array
b[:] = 0.0
ufcx_form, _, _ = ffcx_jit(domain.comm, L, form_compiler_params={"scalar_type": ffcxtype})
kernel_const = getattr(ufcx_form.integrals(0)[0], f"tabulate_tensor_{nptype}")
assemble_vector_ufc(b, kernel_const, (x_dofs, x), dofmap, num_owned_cells)
print(b4.x.array[:])

[0.33333333 0.16666667 0.33333333 0.16666667]


In [23]:
import ctypes
import ctypes.util
import petsc4py.lib
from mpi4py import MPI
from petsc4py import get_config as PETSc_get_config

In [24]:
# Get details of PETSc install
petsc_dir = PETSc_get_config()['PETSC_DIR']
petsc_arch = petsc4py.lib.getPathArchPETSc()[1]

# Get PETSc int and scalar types
if np.dtype(PETSc.ScalarType).kind == 'c':
    complex = True
else:
    complex = False

scalar_size = np.dtype(PETSc.ScalarType).itemsize
index_size = np.dtype(PETSc.IntType).itemsize

if index_size == 8:
    c_int_t = "int64_t"
    ctypes_index = ctypes.c_int64
elif index_size == 4:
    c_int_t = "int32_t"
    ctypes_index = ctypes.c_int32
else:
    raise RuntimeError(f"Cannot translate PETSc index size into a C type, index_size: {index_size}.")

if complex and scalar_size == 16:
    c_scalar_t = "double _Complex"
    numba_scalar_t = numba.types.complex128
elif complex and scalar_size == 8:
    c_scalar_t = "float _Complex"
    numba_scalar_t = numba.types.complex64
elif not complex and scalar_size == 8:
    c_scalar_t = "double"
    numba_scalar_t = numba.types.float64
elif not complex and scalar_size == 4:
    c_scalar_t = "float"
    numba_scalar_t = numba.types.float32
else:
    raise RuntimeError(
        f"Cannot translate PETSc scalar type to a C type, complex: {complex} size: {scalar_size}.")


# Load PETSc library via ctypes
petsc_lib_name = ctypes.util.find_library("petsc")
if petsc_lib_name is not None:
    petsc_lib_ctypes = ctypes.CDLL(petsc_lib_name)
else:
    try:
        petsc_lib_ctypes = ctypes.CDLL(os.path.join(petsc_dir, petsc_arch, "lib", "libpetsc.so"))
    except OSError:
        petsc_lib_ctypes = ctypes.CDLL(os.path.join(petsc_dir, petsc_arch, "lib", "libpetsc.dylib"))
    except OSError:
        print("Could not load PETSc library for CFFI (ABI mode).")
        raise

# Get the PETSc MatSetValuesLocal function via ctypes
MatSetValues_ctypes = petsc_lib_ctypes.MatSetValuesLocal
MatSetValues_ctypes.argtypes = (ctypes.c_void_p, ctypes_index, ctypes.POINTER(
    ctypes_index), ctypes_index, ctypes.POINTER(ctypes_index), ctypes.c_void_p, ctypes.c_int)
del petsc_lib_ctypes



In [25]:
V = fem.FunctionSpace(domain, ("Lagrange", 1))
u, v = ufl.TrialFunction(V), ufl.TestFunction(V)

f = 1
const = fem.Constant(domain, PETSc.ScalarType(f))
a = const*ufl.inner( u, v ) * ufl.dx

ufcx_form, _, _ = ffcx_jit(domain.comm, a, form_compiler_params={"scalar_type": ffcxtype})
kernel_a = getattr(ufcx_form.integrals(0)[0], f"tabulate_tensor_{nptype}")

# @numba.cfunc(c_signature, nopython=True)
# def tabulate_tensor_A(A_, w_, c_, coords_, entity_local_index, permutation):
#     # c = numba.carray(c_, (3, 3), dtype=PETSc.ScalarType)
#     kernel_a(A_, w_, c_, coords_, entity_local_index, permutation)

# integrals = {fem.IntegralType.cell: ([(-1, tabulate_tensor_A.address)], None)}
# a_form = Form_float64([V._cpp_object, V._cpp_object], integrals, [], [C_const._cpp_object], False, None)
A = fem.petsc.assemble_matrix(fem.form(a))
A.assemble()
print(A[:,:])
A.zeroEntries()

@numba.njit
def assemble_ufc(A, kernel, mesh, dofmap, num_cells, set_vals, mode):
    """Assemble provided FFCx/UFC kernel over a mesh into the array b"""
    v, x = mesh
    entity_local_index = np.array([0], dtype=np.intc)
    perm = np.array([0], dtype=np.uint8)
    geometry = np.zeros((3, 3))
    coeffs = np.zeros(1, dtype=PETSc.ScalarType)
    constants = np.array([1], dtype=PETSc.ScalarType)

    A_local = np.zeros((3, 3), dtype=PETSc.ScalarType)
    for cell in range(num_cells):
        # FIXME: This assumes a particular geometry dof layout
        for j in range(3):
            geometry[j] = x[v[cell, j], :]
        # A_local.fill(0.0)
        A_local[:] = 0
        kernel(ffi.from_buffer(A_local), ffi.from_buffer(coeffs),
               ffi.from_buffer(constants),
               ffi.from_buffer(geometry), ffi.from_buffer(entity_local_index),
               ffi.from_buffer(perm))
        rows = cols = dofmap[cell, :]
        print('\n', A_local[:,:])
        set_vals(A, 3, rows.ctypes, 3, cols.ctypes, A_local.ctypes, mode)
        
assemble_ufc(A.handle, kernel_a, (x_dofs, x), dofmap, num_owned_cells, MatSetValues_ctypes, PETSc.InsertMode.ADD_VALUES)
A.assemble()
print('\n', A[:, :])  

[[0.16666667 0.04166667 0.08333333 0.04166667]
 [0.04166667 0.08333333 0.04166667 0.        ]
 [0.08333333 0.04166667 0.16666667 0.04166667]
 [0.04166667 0.         0.04166667 0.08333333]]

 [[0.08333333 0.04166667 0.04166667]
 [0.04166667 0.08333333 0.04166667]
 [0.04166667 0.04166667 0.08333333]]

 [[0.08333333 0.04166667 0.04166667]
 [0.04166667 0.08333333 0.04166667]
 [0.04166667 0.04166667 0.08333333]]

 [[0.16666667 0.04166667 0.08333333 0.04166667]
 [0.04166667 0.08333333 0.04166667 0.        ]
 [0.08333333 0.04166667 0.16666667 0.04166667]
 [0.04166667 0.         0.04166667 0.08333333]]


In [26]:
V = fem.VectorFunctionSpace(domain, ("Lagrange", 1))
u, v = ufl.TrialFunction(V), ufl.TestFunction(V)

a = ufl.inner( u, v ) * ufl.dx

ufcx_form, _, _ = ffcx_jit(domain.comm, a, form_compiler_params={"scalar_type": ffcxtype})
kernel_a = getattr(ufcx_form.integrals(0)[0], f"tabulate_tensor_{nptype}")

# @numba.cfunc(c_signature, nopython=True)
# def tabulate_tensor_A(A_, w_, c_, coords_, entity_local_index, permutation):
#     # c = numba.carray(c_, (3, 3), dtype=PETSc.ScalarType)
#     kernel_a(A_, w_, c_, coords_, entity_local_index, permutation)

# integrals = {fem.IntegralType.cell: ([(-1, tabulate_tensor_A.address)], None)}
# a_form = Form_float64([V._cpp_object, V._cpp_object], integrals, [], [C_const._cpp_object], False, None)
A = fem.petsc.assemble_matrix(fem.form(a))
A.assemble()
print(A[:,:])
A.zeroEntries()

N_dofs_element = V.element.space_dimension
N_sub_spaces = V.num_sub_spaces # V.dofmap.index_map_bs
dofmap = V.dofmap.list.array.reshape(num_cells, int(N_dofs_element/N_sub_spaces))

dofmap_tmp = (N_sub_spaces*np.repeat(dofmap, N_sub_spaces).reshape(-1, N_sub_spaces) + np.arange(N_sub_spaces)).reshape(-1, N_dofs_element).astype(np.dtype(PETSc.IntType))        

@numba.njit
def assemble_ufc(A, kernel, mesh, dofmap, num_cells, set_vals, mode):
    """Assemble provided FFCx/UFC kernel over a mesh into the array b"""
    v, x = mesh
    entity_local_index = np.array([0], dtype=np.intc)
    perm = np.array([0], dtype=np.uint8)
    geometry = np.zeros((3, 3))
    coeffs = np.zeros(2, dtype=PETSc.ScalarType)
    constants = np.array([1, 1], dtype=PETSc.ScalarType)

    A_local = np.zeros((N_dofs_element, N_dofs_element), dtype=PETSc.ScalarType)
    for cell in range(num_cells):
        # FIXME: This assumes a particular geometry dof layout
        for j in range(3):
            geometry[j] = x[v[cell, j], :]
        # A_local.fill(0.0)
        A_local[:] = 0
        kernel(ffi.from_buffer(A_local), ffi.from_buffer(coeffs),
               ffi.from_buffer(constants),
               ffi.from_buffer(geometry), ffi.from_buffer(entity_local_index),
               ffi.from_buffer(perm))
        rows = cols = dofmap[cell, :]
        # print('\n', A_local)
        set_vals(A, N_dofs_element, rows.ctypes, N_dofs_element, cols.ctypes, A_local.ctypes, mode)
        
assemble_ufc(A.handle, kernel_a, (x_dofs, x), dofmap_tmp, num_owned_cells, MatSetValues_ctypes, PETSc.InsertMode.ADD_VALUES)
A.assemble()
print('\n',A[:, :])  

[[0.16666667 0.         0.04166667 0.         0.08333333 0.
  0.04166667 0.        ]
 [0.         0.16666667 0.         0.04166667 0.         0.08333333
  0.         0.04166667]
 [0.04166667 0.         0.08333333 0.         0.04166667 0.
  0.         0.        ]
 [0.         0.04166667 0.         0.08333333 0.         0.04166667
  0.         0.        ]
 [0.08333333 0.         0.04166667 0.         0.16666667 0.
  0.04166667 0.        ]
 [0.         0.08333333 0.         0.04166667 0.         0.16666667
  0.         0.04166667]
 [0.04166667 0.         0.         0.         0.04166667 0.
  0.08333333 0.        ]
 [0.         0.04166667 0.         0.         0.         0.04166667
  0.         0.08333333]]

 [[0.16666667 0.         0.04166667 0.         0.08333333 0.
  0.04166667 0.        ]
 [0.         0.16666667 0.         0.04166667 0.         0.08333333
  0.         0.04166667]
 [0.04166667 0.         0.08333333 0.         0.04166667 0.
  0.         0.        ]
 [0.         0.0416666

In [27]:
A_loc = np.array([[0.08333333, 0.04166667, 0.04166667],
 [0.04166667, 0.08333333, 0.04166667],
 [0.04166667, 0.04166667, 0.08333333]])

A_loc = np.array( [[0.08333333, 0.,         0.04166667, 0.,         0.04166667, 0.],
 [0.,         0.08333333, 0.,         0.04166667, 0.,         0.04166667],
 [0.04166667, 0.,         0.08333333, 0.,         0.04166667, 0.        ],
 [0.,         0.04166667, 0.,         0.08333333, 0.,         0.04166667],
 [0.04166667, 0.,         0.04166667, 0.,         0.08333333, 0.        ],
 [0.,         0.04166667, 0.,         0.04166667, 0.,         0.08333333]])

S1 = np.array([[1,0,0,0],
               [0,1,0,0], 
               [0,0,1,0]])

S2 = np.array([[1,0,0,0],
               [0,0,1,0], 
               [0,0,0,1]])

S1 = np.array([[1,0, 0,0, 0,0, 0,0], 
               [0,1, 0,0, 0,0, 0,0], 
               [0,0, 1,0, 0,0, 0,0], 
               [0,0, 0,1, 0,0, 0,0], 
               [0,0, 0,0, 1,0, 0,0],
               [0,0, 0,0, 0,1, 0,0]])
               
S2 = np.array([[1,0, 0,0, 0,0, 0,0], 
               [0,1, 0,0, 0,0, 0,0], 
               [0,0, 0,0, 0,0, 1,0], 
               [0,0, 0,0, 0,0, 0,1], 
               [0,0, 0,0, 1,0, 0,0],
               [0,0, 0,0, 0,1, 0,0]])               
A1 = S1.T @ A_loc @ S1
A2 = S2.T @ A_loc @ S2
A1+A2

array([[0.16666666, 0.        , 0.04166667, 0.        , 0.08333334,
        0.        , 0.04166667, 0.        ],
       [0.        , 0.16666666, 0.        , 0.04166667, 0.        ,
        0.08333334, 0.        , 0.04166667],
       [0.04166667, 0.        , 0.08333333, 0.        , 0.04166667,
        0.        , 0.        , 0.        ],
       [0.        , 0.04166667, 0.        , 0.08333333, 0.        ,
        0.04166667, 0.        , 0.        ],
       [0.08333334, 0.        , 0.04166667, 0.        , 0.16666666,
        0.        , 0.04166667, 0.        ],
       [0.        , 0.08333334, 0.        , 0.04166667, 0.        ,
        0.16666666, 0.        , 0.04166667],
       [0.04166667, 0.        , 0.        , 0.        , 0.04166667,
        0.        , 0.08333333, 0.        ],
       [0.        , 0.04166667, 0.        , 0.        , 0.        ,
        0.04166667, 0.        , 0.08333333]])

In [28]:
V = fem.VectorFunctionSpace(domain, ("Lagrange", 1))
u, v = ufl.TrialFunction(V), ufl.TestFunction(V)

lambda_ = 1
mu_ = 1
C = np.array([[lambda_ + 2*mu_, lambda_, 0],
              [lambda_, lambda_ + 2*mu_, 0],
              [0, 0, 2*mu_]], dtype=PETSc.ScalarType)
C_const = fem.Constant(domain, C)

coeff1 = fem.Function(fem.FunctionSpace(domain, ('DG', 0)))
coeff2 = fem.Function(fem.FunctionSpace(domain, ('DG', 0)))
coeff1.vector.set(1)
coeff2.vector.set(1)

def epsilon(u):
    return ufl.sym(ufl.grad(u))

def as_2D_tensor(X):
    return ufl.as_tensor([[X[0], X[2]],
                          [X[2], X[1]]])

def sigma(u):
    eps = epsilon(u)
    return as_2D_tensor(C_const * ufl.as_vector([eps[0,0], eps[1,1], eps[0,1]]))

a = ufl.inner( coeff1 * sigma(u), epsilon(v) * coeff2 ) * ufl.dx

ufcx_form, _, _ = ffcx_jit(domain.comm, a, form_compiler_params={"scalar_type": ffcxtype})
kernel_a = getattr(ufcx_form.integrals(0)[0], f"tabulate_tensor_{nptype}")

A = fem.petsc.assemble_matrix(fem.form(a))
A.assemble()
print(A[:,:])
A.zeroEntries()

N_dofs_element = V.element.space_dimension
N_sub_spaces = V.num_sub_spaces # V.dofmap.index_map_bs
dofmap = V.dofmap.list.array.reshape(num_cells, int(N_dofs_element/N_sub_spaces))

dofmap_tmp = (N_sub_spaces*np.repeat(dofmap, N_sub_spaces).reshape(-1, N_sub_spaces) + np.arange(N_sub_spaces)).reshape(-1, N_dofs_element).astype(np.dtype(PETSc.IntType))        

    # map_c = mesh.topology.index_map(mesh.topology.dim)
    # num_cells = map_c.size_local + map_c.num_ghosts
    # cells = np.arange(0, num_cells, dtype=np.int32)

@numba.njit
def assemble_ufc(A, kernel, mesh, dofmap, num_cells, set_vals, mode):
    """Assemble provided FFCx/UFC kernel over a mesh into the array b"""
    v, x = mesh
    entity_local_index = np.array([0], dtype=np.intc)
    perm = np.array([0], dtype=np.uint8)
    geometry = np.zeros((3, 3))
    coeffs = np.array([1, 1], dtype=PETSc.ScalarType)
    constants = C #np.array(C, dtype=PETSc.ScalarType)

    A_local = np.zeros((N_dofs_element, N_dofs_element), dtype=PETSc.ScalarType)
    for cell in range(num_cells):
        # FIXME: This assumes a particular geometry dof layout
        for j in range(3):
            geometry[j] = x[v[cell, j], :]
        # A_local.fill(0.0)
        A_local[:] = 0
        kernel(ffi.from_buffer(A_local), ffi.from_buffer(coeffs),
               ffi.from_buffer(constants),
               ffi.from_buffer(geometry), ffi.from_buffer(entity_local_index),
               ffi.from_buffer(perm))
        rows = cols = dofmap[cell, :]
        # print('\n', A_local)
        set_vals(A, N_dofs_element, rows.ctypes, N_dofs_element, cols.ctypes, A_local.ctypes, mode)
        
assemble_ufc(A.handle, kernel_a, (x_dofs, x), dofmap_tmp, num_owned_cells, MatSetValues_ctypes, PETSc.InsertMode.ADD_VALUES)
A.assemble()
print('\n', A[:, :])  

[[ 2.   0.  -1.5  0.5  0.  -1.  -0.5  0.5]
 [ 0.   2.   0.5 -0.5 -1.   0.   0.5 -1.5]
 [-1.5  0.5  2.  -1.  -0.5  0.5  0.   0. ]
 [ 0.5 -0.5 -1.   2.   0.5 -1.5  0.   0. ]
 [ 0.  -1.  -0.5  0.5  2.   0.  -1.5  0.5]
 [-1.   0.   0.5 -1.5  0.   2.   0.5 -0.5]
 [-0.5  0.5  0.   0.  -1.5  0.5  2.  -1. ]
 [ 0.5 -1.5  0.   0.   0.5 -0.5 -1.   2. ]]

 [[ 2.   0.  -1.5  0.5  0.  -1.  -0.5  0.5]
 [ 0.   2.   0.5 -0.5 -1.   0.   0.5 -1.5]
 [-1.5  0.5  2.  -1.  -0.5  0.5  0.   0. ]
 [ 0.5 -0.5 -1.   2.   0.5 -1.5  0.   0. ]
 [ 0.  -1.  -0.5  0.5  2.   0.  -1.5  0.5]
 [-1.   0.   0.5 -1.5  0.   2.   0.5 -0.5]
 [-0.5  0.5  0.   0.  -1.5  0.5  2.  -1. ]
 [ 0.5 -1.5  0.   0.   0.5 -0.5 -1.   2. ]]


In [30]:
V = fem.VectorFunctionSpace(domain, ("Lagrange", 1))
u, v = ufl.TrialFunction(V), ufl.TestFunction(V)

num_owned_cells = domain.topology.index_map(domain.topology.dim).size_local
num_cells = num_owned_cells + domain.topology.index_map(domain.topology.dim).num_ghosts
x_dofs = domain.geometry.dofmap.array.reshape(num_cells, 3)
x = domain.geometry.x
dofmap = V.dofmap.list.array.reshape(num_cells, 3).astype(np.dtype(PETSc.IntType))


lambda_ = 1
mu_ = 1
DG0 = fem.FunctionSpace(domain, ('DG', 0))
mu_ = fem.Function(DG0)
lambda_ = fem.Function(DG0)
mu_.vector.set(1)
lambda_.vector.set(1)
# rho = 1
# delta = W/L
# gamma = 0.4*delta**2
# beta = 1.25
# mu = 1
# lambda_ = beta
# g = gamma

def epsilon(u):
    return ufl.sym(ufl.grad(u))

def sigma(u):
    return lambda_*ufl.div(u)*ufl.Identity(u.geometric_dimension()) + 2*mu_*epsilon(u)

# Define variational problem
# f = fem.Constant(domain, (PETSc.ScalarType(0), PETSc.ScalarType(-rho*g)))
# b = ufl.inner(f, v)*ufl.dx

a = ufl.inner(sigma(u), epsilon(v)) * ufl.dx


# C = np.array([[lambda_ + 2*mu_, lambda_, 0],
#               [lambda_, lambda_ + 2*mu_, 0],
#               [0, 0, 2*mu_]], dtype=PETSc.ScalarType)
# C_const = fem.Constant(domain, C)

coeff1 = fem.Function(fem.FunctionSpace(domain, ('DG', 0)))
coeff2 = fem.Function(fem.FunctionSpace(domain, ('DG', 0)))
coeff1.vector.set(1)
coeff2.vector.set(1)

# def epsilon(u):
#     return ufl.sym(ufl.grad(u))

# def as_2D_tensor(X):
#     return ufl.as_tensor([[X[0], X[2]],
#                           [X[2], X[1]]])

# def sigma(u):
#     eps = epsilon(u)
#     return as_2D_tensor(C_const * ufl.as_vector([eps[0,0], eps[1,1], eps[0,1]]))

# a = ufl.inner( sigma(u), epsilon(v) ) * ufl.dx

ufcx_form, _, _ = ffcx_jit(domain.comm, a, form_compiler_params={"scalar_type": ffcxtype})
kernel_a = getattr(ufcx_form.integrals(0)[0], f"tabulate_tensor_{nptype}")

A = fem.petsc.assemble_matrix(fem.form(a))
A.assemble()
print(A[:,:])
A.zeroEntries()

N_dofs_element = V.element.space_dimension
N_sub_spaces = V.num_sub_spaces # V.dofmap.index_map_bs
dofmap = V.dofmap.list.array.reshape(num_cells, int(N_dofs_element/N_sub_spaces))

dofmap_tmp = (N_sub_spaces*np.repeat(dofmap, N_sub_spaces).reshape(-1, N_sub_spaces) + np.arange(N_sub_spaces)).reshape(-1, N_dofs_element).astype(np.dtype(PETSc.IntType))        

    # map_c = mesh.topology.index_map(mesh.topology.dim)
    # num_cells = map_c.size_local + map_c.num_ghosts
    # cells = np.arange(0, num_cells, dtype=np.int32)

@numba.njit
def assemble_ufc(A, kernel, mesh, dofmap, num_cells, set_vals, mode):
    """Assemble provided FFCx/UFC kernel over a mesh into the array b"""
    v, x = mesh
    entity_local_index = np.array([0], dtype=np.intc)
    perm = np.array([0], dtype=np.uint8)
    geometry = np.zeros((3, 3))
    coeffs = np.array([1, 1], dtype=PETSc.ScalarType)
    constants = C #np.array(C, dtype=PETSc.ScalarType)

    A_local = np.zeros((N_dofs_element, N_dofs_element), dtype=PETSc.ScalarType)
    for cell in range(num_cells):
        geometry[:] = x[v[cell, :], :]
        A_local.fill(0.0)
        
        kernel(ffi.from_buffer(A_local), ffi.from_buffer(coeffs),
               ffi.from_buffer(constants),
               ffi.from_buffer(geometry), ffi.from_buffer(entity_local_index),
               ffi.from_buffer(perm))
        rows = cols = dofmap[cell, :]
        # print('\n', A_local)
        set_vals(A, N_dofs_element, rows.ctypes, N_dofs_element, cols.ctypes, A_local.ctypes, mode)
        
assemble_ufc(A.handle, kernel_a, (x_dofs, x), dofmap_tmp, num_owned_cells, MatSetValues_ctypes, PETSc.InsertMode.ADD_VALUES)
A.assemble()
print('\n', A[:, :])  

[[ 2.   0.  -1.5  0.5  0.  -1.  -0.5  0.5]
 [ 0.   2.   0.5 -0.5 -1.   0.   0.5 -1.5]
 [-1.5  0.5  2.  -1.  -0.5  0.5  0.   0. ]
 [ 0.5 -0.5 -1.   2.   0.5 -1.5  0.   0. ]
 [ 0.  -1.  -0.5  0.5  2.   0.  -1.5  0.5]
 [-1.   0.   0.5 -1.5  0.   2.   0.5 -0.5]
 [-0.5  0.5  0.   0.  -1.5  0.5  2.  -1. ]
 [ 0.5 -1.5  0.   0.   0.5 -0.5 -1.   2. ]]

 [[ 2.   0.  -1.5  0.5  0.  -1.  -0.5  0.5]
 [ 0.   2.   0.5 -0.5 -1.   0.   0.5 -1.5]
 [-1.5  0.5  2.  -1.  -0.5  0.5  0.   0. ]
 [ 0.5 -0.5 -1.   2.   0.5 -1.5  0.   0. ]
 [ 0.  -1.  -0.5  0.5  2.   0.  -1.5  0.5]
 [-1.   0.   0.5 -1.5  0.   2.   0.5 -0.5]
 [-0.5  0.5  0.   0.  -1.5  0.5  2.  -1. ]
 [ 0.5 -1.5  0.   0.   0.5 -0.5 -1.   2. ]]
